import type { Metadata } from 'next';
import './globals.css';

import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['400'], // Specify weights as Roboto is not a variable font
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Stackskills',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>{children}</body>
    </html>
  );
}
